FROM oven/bun AS base

# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

# Install dependencies
COPY ./package.json ./bun.lock ./

# Copy necessary packages or whole repo
# To reduce disk space, copy only those that are used
COPY ./apps/web ./apps/web
COPY ./packages/ui ./packages/ui

# Change directory to web
WORKDIR /app/apps/web

RUN ls -l

# Install all dependencies
RUN bun install


# Build application
RUN bun run build


FROM base AS runner

ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER nextjs


COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public apps/web/public
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static apps/web/.next/static

# COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
# COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./.next/static
# COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./public

ENV HOSTNAME=0.0.0.0
ENV NODE_ENV=production

CMD ["bun", "apps/web/server.js"]
