FROM oven/bun AS base

# Rebuild the source code only when needed
FROM base AS builder

WORKDIR /app

# Install dependencies
COPY ./package.json ./bun.lock ./


COPY ./apps/web ./apps/web
COPY ./packages/shared-ui ./packages/shared-ui

# Change directory to web
WORKDIR /app/apps/web

RUN ls -l

# Install all dependencies
RUN bun install

# Debug build
ENV DEBUG=*

# Build application
RUN bun run build


FROM base AS runner

ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_API_URL

ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

USER nextjs

COPY --from=builder /app/apps/web/public ./public

COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./public

ENV HOSTNAME=0.0.0.0
ENV NODE_ENV=production

CMD ["bun", "server.js"]
