// This file is auto-generated by @hey-api/openapi-ts

export const ClientSchema = {
  type: "object",
  properties: {
    id: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    companyName: {
      type: "string",
    },
    contactName: {
      type: "string",
    },
    email: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      type: "Date",
    },
  },
  required: ["id", "companyName", "contactName", "email", "createdAt"],
  $id: "#/components/schemas/Client",
} as const;

export const Client__Schema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      id: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      companyName: {
        type: "string",
      },
      contactName: {
        type: "string",
      },
      email: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
      },
      createdAt: {
        type: "Date",
      },
    },
    required: ["id", "companyName", "contactName", "email", "createdAt"],
    $id: "#/components/schemas/Client",
  },
  $id: "#/components/schemas/Client[]",
} as const;

export const ProjectSchema = {
  type: "object",
  properties: {
    id: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      type: "Date",
    },
    client: {
      anyOf: [
        {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            companyName: {
              type: "string",
            },
            contactName: {
              type: "string",
            },
            email: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            createdAt: {
              type: "Date",
            },
          },
          required: ["id", "companyName", "contactName", "email", "createdAt"],
          $id: "#/components/schemas/Client",
        },
        {
          type: "null",
        },
      ],
    },
  },
  required: ["id", "title", "createdAt", "client"],
  $id: "#/components/schemas/Project",
} as const;

export const Project__Schema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      id: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      title: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
      },
      createdAt: {
        type: "Date",
      },
      client: {
        anyOf: [
          {
            type: "object",
            properties: {
              id: {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              companyName: {
                type: "string",
              },
              contactName: {
                type: "string",
              },
              email: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              createdAt: {
                type: "Date",
              },
            },
            required: [
              "id",
              "companyName",
              "contactName",
              "email",
              "createdAt",
            ],
            $id: "#/components/schemas/Client",
          },
          {
            type: "null",
          },
        ],
      },
    },
    required: ["id", "title", "createdAt", "client"],
    $id: "#/components/schemas/Project",
  },
  $id: "#/components/schemas/Project[]",
} as const;

export const ProjectCountSchema = {
  type: "object",
  properties: {
    count: {
      type: "number",
    },
  },
  required: ["count"],
  $id: "#/components/schemas/ProjectCount",
} as const;

export const TimeEntrySchema = {
  type: "object",
  properties: {
    id: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    startAt: {
      anyOf: [
        {
          type: "Date",
        },
        {
          type: "null",
        },
      ],
    },
    endAt: {
      anyOf: [
        {
          type: "Date",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      type: "Date",
    },
    project: {
      anyOf: [
        {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            createdAt: {
              type: "Date",
            },
            client: {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    id: {
                      minimum: -2147483648,
                      maximum: 2147483647,
                      type: "integer",
                    },
                    companyName: {
                      type: "string",
                    },
                    contactName: {
                      type: "string",
                    },
                    email: {
                      anyOf: [
                        {
                          type: "string",
                        },
                        {
                          type: "null",
                        },
                      ],
                    },
                    createdAt: {
                      type: "Date",
                    },
                  },
                  required: [
                    "id",
                    "companyName",
                    "contactName",
                    "email",
                    "createdAt",
                  ],
                  $id: "#/components/schemas/Client",
                },
                {
                  type: "null",
                },
              ],
            },
          },
          required: ["id", "title", "createdAt", "client"],
          $id: "#/components/schemas/Project",
        },
        {
          type: "null",
        },
      ],
    },
    projectTask: {
      anyOf: [
        {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            title: {
              type: "string",
            },
            description: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            createdAt: {
              type: "Date",
            },
          },
          required: ["id", "title", "description", "createdAt"],
        },
        {
          type: "null",
        },
      ],
    },
  },
  required: [
    "id",
    "title",
    "startAt",
    "endAt",
    "createdAt",
    "project",
    "projectTask",
  ],
  $id: "#/components/schemas/TimeEntry",
} as const;

export const TimeEntry__Schema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      id: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      title: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
      },
      startAt: {
        anyOf: [
          {
            type: "Date",
          },
          {
            type: "null",
          },
        ],
      },
      endAt: {
        anyOf: [
          {
            type: "Date",
          },
          {
            type: "null",
          },
        ],
      },
      createdAt: {
        type: "Date",
      },
      project: {
        anyOf: [
          {
            type: "object",
            properties: {
              id: {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              title: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              createdAt: {
                type: "Date",
              },
              client: {
                anyOf: [
                  {
                    type: "object",
                    properties: {
                      id: {
                        minimum: -2147483648,
                        maximum: 2147483647,
                        type: "integer",
                      },
                      companyName: {
                        type: "string",
                      },
                      contactName: {
                        type: "string",
                      },
                      email: {
                        anyOf: [
                          {
                            type: "string",
                          },
                          {
                            type: "null",
                          },
                        ],
                      },
                      createdAt: {
                        type: "Date",
                      },
                    },
                    required: [
                      "id",
                      "companyName",
                      "contactName",
                      "email",
                      "createdAt",
                    ],
                    $id: "#/components/schemas/Client",
                  },
                  {
                    type: "null",
                  },
                ],
              },
            },
            required: ["id", "title", "createdAt", "client"],
            $id: "#/components/schemas/Project",
          },
          {
            type: "null",
          },
        ],
      },
      projectTask: {
        anyOf: [
          {
            type: "object",
            properties: {
              id: {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              title: {
                type: "string",
              },
              description: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              createdAt: {
                type: "Date",
              },
            },
            required: ["id", "title", "description", "createdAt"],
          },
          {
            type: "null",
          },
        ],
      },
    },
    required: [
      "id",
      "title",
      "startAt",
      "endAt",
      "createdAt",
      "project",
      "projectTask",
    ],
    $id: "#/components/schemas/TimeEntry",
  },
  $id: "#/components/schemas/TimeEntry[]",
} as const;

export const TimeEntryDurationByDateSchema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      date: {
        anyOf: [
          {
            type: "Date",
          },
          {
            format: "date-time",
            type: "string",
          },
          {
            format: "date",
            type: "string",
          },
          {
            type: "number",
          },
        ],
      },
      duration: {
        type: "number",
      },
    },
    required: ["date", "duration"],
  },
  $id: "#/components/schemas/TimeEntryDurationByDate",
} as const;

export const ProjectTaskSchema = {
  type: "object",
  properties: {
    id: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    title: {
      type: "string",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    createdAt: {
      type: "Date",
    },
    project: {
      type: "object",
      properties: {
        id: {
          minimum: -2147483648,
          maximum: 2147483647,
          type: "integer",
        },
        title: {
          anyOf: [
            {
              type: "string",
            },
            {
              type: "null",
            },
          ],
        },
        createdAt: {
          type: "Date",
        },
        client: {
          anyOf: [
            {
              type: "object",
              properties: {
                id: {
                  minimum: -2147483648,
                  maximum: 2147483647,
                  type: "integer",
                },
                companyName: {
                  type: "string",
                },
                contactName: {
                  type: "string",
                },
                email: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                },
                createdAt: {
                  type: "Date",
                },
              },
              required: [
                "id",
                "companyName",
                "contactName",
                "email",
                "createdAt",
              ],
              $id: "#/components/schemas/Client",
            },
            {
              type: "null",
            },
          ],
        },
      },
      required: ["id", "title", "createdAt", "client"],
      $id: "#/components/schemas/Project",
    },
  },
  required: ["id", "title", "description", "createdAt", "project"],
  $id: "#/components/schemas/ProjectTask",
} as const;

export const ProjectTask__Schema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      id: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      title: {
        type: "string",
      },
      description: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
      },
      createdAt: {
        type: "Date",
      },
      project: {
        type: "object",
        properties: {
          id: {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          title: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
          },
          createdAt: {
            type: "Date",
          },
          client: {
            anyOf: [
              {
                type: "object",
                properties: {
                  id: {
                    minimum: -2147483648,
                    maximum: 2147483647,
                    type: "integer",
                  },
                  companyName: {
                    type: "string",
                  },
                  contactName: {
                    type: "string",
                  },
                  email: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                  },
                  createdAt: {
                    type: "Date",
                  },
                },
                required: [
                  "id",
                  "companyName",
                  "contactName",
                  "email",
                  "createdAt",
                ],
                $id: "#/components/schemas/Client",
              },
              {
                type: "null",
              },
            ],
          },
        },
        required: ["id", "title", "createdAt", "client"],
        $id: "#/components/schemas/Project",
      },
    },
    required: ["id", "title", "description", "createdAt", "project"],
    $id: "#/components/schemas/ProjectTask",
  },
  $id: "#/components/schemas/ProjectTask[]",
} as const;

export const ProjectTaskCountSchema = {
  type: "object",
  properties: {
    count: {
      type: "number",
    },
  },
  required: ["count"],
  $id: "#/components/schemas/ProjectTaskCount",
} as const;

export const InvoiceSchema = {
  type: "object",
  properties: {
    id: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    clientId: {
      anyOf: [
        {
          minimum: -2147483648,
          maximum: 2147483647,
          type: "integer",
        },
        {
          type: "null",
        },
      ],
    },
    projectId: {
      anyOf: [
        {
          minimum: -2147483648,
          maximum: 2147483647,
          type: "integer",
        },
        {
          type: "null",
        },
      ],
    },
    amount: {
      minimum: -2147483648,
      maximum: 2147483647,
      type: "integer",
    },
    currency: {
      anyOf: [
        {
          const: "czk",
          type: "string",
        },
        {
          const: "eur",
          type: "string",
        },
        {
          const: "usd",
          type: "string",
        },
      ],
    },
    dueDate: {
      anyOf: [
        {
          type: "Date",
        },
        {
          type: "null",
        },
      ],
    },
    paidAt: {
      anyOf: [
        {
          type: "Date",
        },
        {
          type: "null",
        },
      ],
    },
    sentAt: {
      anyOf: [
        {
          type: "Date",
        },
        {
          type: "null",
        },
      ],
    },
    issuedAt: {
      type: "Date",
    },
    createdAt: {
      type: "Date",
    },
    updatedAt: {
      type: "Date",
    },
    ownerId: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
    },
    project: {
      anyOf: [
        {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            ownerId: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            clientId: {
              anyOf: [
                {
                  minimum: -2147483648,
                  maximum: 2147483647,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
            },
            createdAt: {
              type: "Date",
            },
          },
          required: ["id", "title", "ownerId", "clientId", "createdAt"],
        },
        {
          type: "null",
        },
      ],
    },
    client: {
      anyOf: [
        {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            companyName: {
              type: "string",
            },
            contactName: {
              type: "string",
            },
            email: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            ownerId: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
            },
            createdAt: {
              type: "Date",
            },
          },
          required: [
            "id",
            "companyName",
            "contactName",
            "email",
            "ownerId",
            "createdAt",
          ],
        },
        {
          type: "null",
        },
      ],
    },
    items: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          projectTaskId: {
            anyOf: [
              {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              {
                type: "null",
              },
            ],
          },
          name: {
            type: "string",
          },
          qty: {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          unitPrice: {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          invoiceId: {
            anyOf: [
              {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              {
                type: "null",
              },
            ],
          },
          projectTask: {
            anyOf: [
              {
                type: "object",
                properties: {
                  id: {
                    minimum: -2147483648,
                    maximum: 2147483647,
                    type: "integer",
                  },
                  title: {
                    type: "string",
                  },
                  projectId: {
                    minimum: -2147483648,
                    maximum: 2147483647,
                    type: "integer",
                  },
                  description: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                  },
                  createdAt: {
                    type: "Date",
                  },
                },
                required: [
                  "id",
                  "title",
                  "projectId",
                  "description",
                  "createdAt",
                ],
              },
              {
                type: "null",
              },
            ],
          },
        },
        required: [
          "id",
          "projectTaskId",
          "name",
          "qty",
          "unitPrice",
          "invoiceId",
          "projectTask",
        ],
      },
    },
  },
  required: [
    "id",
    "clientId",
    "projectId",
    "amount",
    "currency",
    "dueDate",
    "paidAt",
    "sentAt",
    "issuedAt",
    "createdAt",
    "updatedAt",
    "ownerId",
    "project",
    "client",
    "items",
  ],
  $id: "#/components/schemas/Invoice",
} as const;

export const Invoice__Schema = {
  type: "array",
  items: {
    type: "object",
    properties: {
      id: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      clientId: {
        anyOf: [
          {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          {
            type: "null",
          },
        ],
      },
      projectId: {
        anyOf: [
          {
            minimum: -2147483648,
            maximum: 2147483647,
            type: "integer",
          },
          {
            type: "null",
          },
        ],
      },
      amount: {
        minimum: -2147483648,
        maximum: 2147483647,
        type: "integer",
      },
      currency: {
        anyOf: [
          {
            const: "czk",
            type: "string",
          },
          {
            const: "eur",
            type: "string",
          },
          {
            const: "usd",
            type: "string",
          },
        ],
      },
      dueDate: {
        anyOf: [
          {
            type: "Date",
          },
          {
            type: "null",
          },
        ],
      },
      paidAt: {
        anyOf: [
          {
            type: "Date",
          },
          {
            type: "null",
          },
        ],
      },
      sentAt: {
        anyOf: [
          {
            type: "Date",
          },
          {
            type: "null",
          },
        ],
      },
      issuedAt: {
        type: "Date",
      },
      createdAt: {
        type: "Date",
      },
      updatedAt: {
        type: "Date",
      },
      ownerId: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "null",
          },
        ],
      },
      project: {
        anyOf: [
          {
            type: "object",
            properties: {
              id: {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              title: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              ownerId: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              clientId: {
                anyOf: [
                  {
                    minimum: -2147483648,
                    maximum: 2147483647,
                    type: "integer",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              createdAt: {
                type: "Date",
              },
            },
            required: ["id", "title", "ownerId", "clientId", "createdAt"],
          },
          {
            type: "null",
          },
        ],
      },
      client: {
        anyOf: [
          {
            type: "object",
            properties: {
              id: {
                minimum: -2147483648,
                maximum: 2147483647,
                type: "integer",
              },
              companyName: {
                type: "string",
              },
              contactName: {
                type: "string",
              },
              email: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              ownerId: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
              },
              createdAt: {
                type: "Date",
              },
            },
            required: [
              "id",
              "companyName",
              "contactName",
              "email",
              "ownerId",
              "createdAt",
            ],
          },
          {
            type: "null",
          },
        ],
      },
      items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            id: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            projectTaskId: {
              anyOf: [
                {
                  minimum: -2147483648,
                  maximum: 2147483647,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
            },
            name: {
              type: "string",
            },
            qty: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            unitPrice: {
              minimum: -2147483648,
              maximum: 2147483647,
              type: "integer",
            },
            invoiceId: {
              anyOf: [
                {
                  minimum: -2147483648,
                  maximum: 2147483647,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
            },
            projectTask: {
              anyOf: [
                {
                  type: "object",
                  properties: {
                    id: {
                      minimum: -2147483648,
                      maximum: 2147483647,
                      type: "integer",
                    },
                    title: {
                      type: "string",
                    },
                    projectId: {
                      minimum: -2147483648,
                      maximum: 2147483647,
                      type: "integer",
                    },
                    description: {
                      anyOf: [
                        {
                          type: "string",
                        },
                        {
                          type: "null",
                        },
                      ],
                    },
                    createdAt: {
                      type: "Date",
                    },
                  },
                  required: [
                    "id",
                    "title",
                    "projectId",
                    "description",
                    "createdAt",
                  ],
                },
                {
                  type: "null",
                },
              ],
            },
          },
          required: [
            "id",
            "projectTaskId",
            "name",
            "qty",
            "unitPrice",
            "invoiceId",
            "projectTask",
          ],
        },
      },
    },
    required: [
      "id",
      "clientId",
      "projectId",
      "amount",
      "currency",
      "dueDate",
      "paidAt",
      "sentAt",
      "issuedAt",
      "createdAt",
      "updatedAt",
      "ownerId",
      "project",
      "client",
      "items",
    ],
  },
  $id: "#/components/schemas/Invoice[]",
} as const;

export const UserSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    name: {
      type: "string",
    },
    email: {
      type: "string",
    },
    emailVerified: {
      type: "boolean",
    },
    image: {
      type: "string",
    },
    createdAt: {
      type: "date",
    },
    updatedAt: {
      type: "date",
    },
  },
} as const;

export const SessionSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    expiresAt: {
      type: "date",
    },
    token: {
      type: "string",
    },
    createdAt: {
      type: "date",
    },
    updatedAt: {
      type: "date",
    },
    ipAddress: {
      type: "string",
    },
    userAgent: {
      type: "string",
    },
    userId: {
      type: "string",
    },
  },
} as const;

export const AccountSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    accountId: {
      type: "string",
    },
    providerId: {
      type: "string",
    },
    userId: {
      type: "string",
    },
    accessToken: {
      type: "string",
    },
    refreshToken: {
      type: "string",
    },
    idToken: {
      type: "string",
    },
    accessTokenExpiresAt: {
      type: "date",
    },
    refreshTokenExpiresAt: {
      type: "date",
    },
    scope: {
      type: "string",
    },
    password: {
      type: "string",
    },
    createdAt: {
      type: "date",
    },
    updatedAt: {
      type: "date",
    },
  },
} as const;

export const VerificationSchema = {
  type: "object",
  properties: {
    id: {
      type: "string",
    },
    identifier: {
      type: "string",
    },
    value: {
      type: "string",
    },
    expiresAt: {
      type: "date",
    },
    createdAt: {
      type: "date",
    },
    updatedAt: {
      type: "date",
    },
  },
} as const;
