services:
  # Local database for development
  database:
    image: postgres:17.5
    env_file:
      - .env
      - .env.example
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
    volumes:
      - database:/var/lib/postgresql/data

  redis:
    image: redis:8.0.3-alpine
    ports:
      - 6379:6379

volumes:
  database: