import { AppSidebar } from "@/components/app-sidebar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import VersionTag from "@/components/version-tag";
import config from "@/config/app";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: `${config.AppName} | App`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="aliased">
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full h-full">
            <SidebarInset>
              <SidebarTrigger className="m-2 size-10" />
              {children}
            </SidebarInset>
            <VersionTag />
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
